spring:
  application:
    name: product-data
  datasource:    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
    hibernate:      ddl-auto: update    show-sql: true
    properties:      format-sql: true